#!/usr/bin/env bash
set -euo pipefail

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

echo -e "${BLUE}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║     Cyprus Invoice Fixer Setup       ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${NC}"

if [ -f ".env" ]; then
  echo -e "${YELLOW}⚠  .env already exists. Overwrite? (y/N)${NC}"
  read -r overwrite
  [[ "$overwrite" =~ ^[Yy]$ ]] || { echo "Keeping existing .env."; exec_compose; exit 0; }
fi

echo -e "\n${BLUE}── Database ────────────────────────────${NC}"
read -rp "Postgres password [changeme]: " POSTGRES_PASSWORD
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}

echo -e "\n${BLUE}── JWT ─────────────────────────────────${NC}"
JWT_SECRET=$(openssl rand -base64 48 2>/dev/null || head -c 48 /dev/urandom | base64)
echo -e "  ${GREEN}✓ JWT secret auto-generated${NC}"

echo -e "\n${BLUE}── AI Provider ─────────────────────────${NC}"
echo "  1) OpenAI (GPT-4o-mini)  2) Ollama (local, free)"
read -rp "Choose [1]: " ai_choice
ai_choice=${ai_choice:-1}

if [ "$ai_choice" = "1" ]; then
  AI_PROVIDER=openai
  read -rp "OpenAI API key (sk-...): " OPENAI_API_KEY
  OLLAMA_BASE_URL=""
  OLLAMA_MODEL=""
else
  AI_PROVIDER=ollama
  OPENAI_API_KEY=""
  OLLAMA_BASE_URL="http://ollama:11434"
  read -rp "Ollama model [llama3]: " OLLAMA_MODEL
  OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
fi

echo -e "\n${BLUE}── Stripe (optional — skip for free-tier only) ──${NC}"
read -rp "Stripe secret key (sk_live/sk_test or leave blank): " STRIPE_SECRET_KEY
read -rp "Stripe webhook secret (whsec_... or leave blank): " STRIPE_WEBHOOK_SECRET
read -rp "Stripe price ID (price_... or leave blank): " STRIPE_PRICE_ID

echo -e "\n${BLUE}── URLs ────────────────────────────────${NC}"
read -rp "Frontend URL [http://localhost:3000]: " FRONTEND_URL
FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}

cat > .env <<EOF
# Generated by setup.sh
POSTGRES_USER=appuser
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_ISSUER=CyprusInvoiceFixer
JWT_AUDIENCE=CyprusInvoiceFixerUsers

AI_PROVIDER=${AI_PROVIDER}
OPENAI_API_KEY=${OPENAI_API_KEY}
OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
OLLAMA_MODEL=${OLLAMA_MODEL}

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_PRICE_ID=${STRIPE_PRICE_ID}

FRONTEND_URL=${FRONTEND_URL}
NEXT_PUBLIC_API_URL=http://localhost:5000
EOF

echo -e "\n${GREEN}✓ .env created${NC}"

exec_compose() {
  if [ "${AI_PROVIDER:-openai}" = "ollama" ]; then
    COMPOSE_PROFILES=ollama docker compose up --build -d
    echo -e "${YELLOW}⚡ Pulling Ollama model ${OLLAMA_MODEL}...${NC}"
    sleep 5
    docker compose exec ollama ollama pull "${OLLAMA_MODEL}" || true
  else
    docker compose up --build -d
  fi
}

exec_compose

echo -e "
${GREEN}╔══════════════════════════════════════╗
║  ✅ Cyprus Invoice Fixer is running! ║
╠══════════════════════════════════════╣
║  Frontend : ${FRONTEND_URL}
║  API/Docs : http://localhost:5000/swagger
╚══════════════════════════════════════╝${NC}
"
