// <auto-generated />
using System;
using CyprusInvoiceFixer.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyprusInvoiceFixer.Core.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.8").HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.User", b => {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("FullName").HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
            b.Property<string>("Plan").IsRequired().HasColumnType("text");
            b.Property<int>("MonthlyUsageCount").HasColumnType("integer");
            b.Property<DateTime>("UsageResetAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id"); b.HasIndex("Email").IsUnique(); b.ToTable("Users");
        });
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.Invoice", b => {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<string>("SupplierName").HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("SupplierVatNumber").HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<string>("SupplierAddress").HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<string>("CustomerName").HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("CustomerVatNumber").HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<string>("CustomerAddress").HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<string>("InvoiceNumber").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<DateTime?>("InvoiceDate").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("DueDate").HasColumnType("timestamp with time zone");
            b.Property<decimal>("Subtotal").HasPrecision(18,4).HasColumnType("numeric(18,4)");
            b.Property<decimal>("VatRate").HasPrecision(5,2).HasColumnType("numeric(5,2)");
            b.Property<decimal>("VatAmount").HasPrecision(18,4).HasColumnType("numeric(18,4)");
            b.Property<decimal>("Total").HasPrecision(18,4).HasColumnType("numeric(18,4)");
            b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<string>("RawInput").HasColumnType("text");
            b.Property<string>("AiNotes").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id"); b.HasIndex("UserId"); b.ToTable("Invoices");
        });
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.InvoiceLineItem", b => {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("InvoiceId").HasColumnType("uuid");
            b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<decimal>("Quantity").HasPrecision(18,4).HasColumnType("numeric(18,4)");
            b.Property<decimal>("UnitPrice").HasPrecision(18,4).HasColumnType("numeric(18,4)");
            b.HasKey("Id"); b.HasIndex("InvoiceId"); b.ToTable("InvoiceLineItems");
        });
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.ValidationIssue", b => {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("InvoiceId").HasColumnType("uuid");
            b.Property<string>("Field").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("Severity").IsRequired().HasColumnType("text");
            b.HasKey("Id"); b.HasIndex("InvoiceId"); b.ToTable("ValidationIssues");
        });
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.Invoice", b => { b.HasOne("CyprusInvoiceFixer.Core.Models.User","User").WithMany("Invoices").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("User"); });
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.InvoiceLineItem", b => { b.HasOne("CyprusInvoiceFixer.Core.Models.Invoice","Invoice").WithMany("LineItems").HasForeignKey("InvoiceId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("Invoice"); });
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.ValidationIssue", b => { b.HasOne("CyprusInvoiceFixer.Core.Models.Invoice","Invoice").WithMany("ValidationIssues").HasForeignKey("InvoiceId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("Invoice"); });
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.User", b => b.Navigation("Invoices"));
        modelBuilder.Entity("CyprusInvoiceFixer.Core.Models.Invoice", b => { b.Navigation("LineItems"); b.Navigation("ValidationIssues"); });
#pragma warning restore 612, 618
    }
}
