using CyprusInvoiceFixer.Core.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CyprusInvoiceFixer.Core.Services;

public class PdfService : IPdfService
{
    public byte[] GenerateInvoicePdf(Invoice invoice)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10).FontFamily(Fonts.Arial));

                page.Header().Column(col =>
                {
                    col.Item().Text("TAX INVOICE").FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
                    col.Item().Text($"Invoice #: {invoice.InvoiceNumber ?? "N/A"}").FontSize(12);
                    col.Item().Text($"Date: {invoice.InvoiceDate?.ToString("dd/MM/yyyy") ?? "N/A"}");
                    if (invoice.DueDate.HasValue)
                        col.Item().Text($"Due Date: {invoice.DueDate.Value:dd/MM/yyyy}");
                });

                page.Content().PaddingTop(20).Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("FROM").Bold();
                            c.Item().Text(invoice.SupplierName ?? "-");
                            if (!string.IsNullOrWhiteSpace(invoice.SupplierVatNumber))
                                c.Item().Text($"VAT: {invoice.SupplierVatNumber}");
                            c.Item().Text(invoice.SupplierAddress ?? "");
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("TO").Bold();
                            c.Item().Text(invoice.CustomerName ?? "-");
                            if (!string.IsNullOrWhiteSpace(invoice.CustomerVatNumber))
                                c.Item().Text($"VAT: {invoice.CustomerVatNumber}");
                            c.Item().Text(invoice.CustomerAddress ?? "");
                        });
                    });

                    col.Item().PaddingTop(20).Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(4);
                            cols.RelativeColumn();
                            cols.RelativeColumn();
                            cols.RelativeColumn();
                        });
                        table.Header(h =>
                        {
                            h.Cell().Background(Colors.Grey.Lighten2).Padding(4).Text("Description").Bold();
                            h.Cell().Background(Colors.Grey.Lighten2).Padding(4).Text("Qty").Bold();
                            h.Cell().Background(Colors.Grey.Lighten2).Padding(4).Text("Unit Price").Bold();
                            h.Cell().Background(Colors.Grey.Lighten2).Padding(4).Text("Total").Bold();
                        });
                        foreach (var item in invoice.LineItems)
                        {
                            table.Cell().Padding(4).Text(item.Description);
                            table.Cell().Padding(4).Text(item.Quantity.ToString("G"));
                            table.Cell().Padding(4).Text($"{invoice.Currency} {item.UnitPrice:F2}");
                            table.Cell().Padding(4).Text($"{invoice.Currency} {item.LineTotal:F2}");
                        }
                    });

                    col.Item().PaddingTop(10).AlignRight().Column(c =>
                    {
                        c.Item().Text($"Subtotal: {invoice.Currency} {invoice.Subtotal:F2}");
                        c.Item().Text($"VAT ({invoice.VatRate}%): {invoice.Currency} {invoice.VatAmount:F2}");
                        c.Item().Text($"TOTAL: {invoice.Currency} {invoice.Total:F2}").Bold().FontSize(12);
                    });

                    if (!string.IsNullOrWhiteSpace(invoice.AiNotes))
                        col.Item().PaddingTop(20)
                            .Background(Colors.Yellow.Lighten3).Padding(8)
                            .Text($"AI Notes: {invoice.AiNotes}").FontSize(9).Italic();
                });

                page.Footer().AlignCenter().Text(t =>
                    t.Span("Generated by Cyprus Invoice Fixer").FontSize(8).FontColor(Colors.Grey.Medium));
            });
        });
        return doc.GeneratePdf();
    }
}
